### ISSUE TITLE
Question about repetitions for MEG data

### ISSUE THREAD

**Issue by Aceticia** [Singerjohannes/object_drawing_dynamics#1]
Hi, this is a fantastic work and I'm working on analyzing some of your MEG data. I have some simple questions about your data's shape, hope you can answer it. Thank you so much.

I'm trying to understand why the number of repetitions is 24. If I'm understanding the description in the paper correctly, each category of image is presented in 3 separate runs, and each run would include 8 times? 

My second question is: Is this ordering in terms of absolute time? So repetition 1 happened before repetition 2, for example?

**Comment by Singerjohannes** [comment]
Hey, thanks for the interest in our work! 

You're right about the number of repetitions per image. There were 3 runs for each type of depiction (photo, drawing, sketch) and in each run each image was repeated 8 times. That means 3*8=24 repetitions per image in total. 

And about the trial ordering, as far as I know the order of trials in the preprocessed data should directly correspond to the order of trials in the experiment. If you're preprocessing the data yourself then the events in the trigger channel in the MEG data give you the information about when a certain image was shown in the experiment. 

Let me know if there are any other questions :)

**Comment by Aceticia** [comment]
Thanks for the quick reply! This answers my question. Another question: is there a fixed order to the 3 types of depictions, so something like photos before drawing? Or is this random for each subject?

**Comment by Aceticia** [comment]
Ah and another question - sorry for spamming, I'm wondering what is the image order in the data? There is index but I didn't find anything that maps from the category index to the image names.

**Comment by Singerjohannes** [comment]
The order of the type of depiction was fully randomized. But you can look up which type of images were presented by inspecting the events.tsv files available via OpenNeuro. The image number (1-48) corresponds to the alphabetic ordering of images in the stimulus folder on OSF. Hope this helps :)
